### ISSUE TITLE
课程跳转有BUG

### ISSUE THREAD

**Issue by CN-Cyber-Jacky** [CTeX-org/learnlatex.github.io#13]
在网页版中，直接点击下一课、最后一课之类的链接时，页面显示404，观察发现是链接缺少.md后缀。

**Comment by stone-zeng** [comment]
如果指的是 markdown 文件里面的超链接的话，这个是 by design 的，因为它们本意不是用来直接阅读，而是会被编译为 html 文件最终作为网页显示。
